[Service]
Environment=BUILDKITE_ENABLE_ENVIRONMENT_VARIABLE_ALLOWLIST=true
Environment=BUILDKITE_ALLOWED_ENVIRONMENT_VARIABLES=^LANG$,^LC_ALL$,^PYTHONDONTWRITEBYTECODE$,^HP_BUILDKITE_CHECK$,^HP_BUILDKITE_OS$
Restart=no
ExecStartPost=
ExecStopPost=+/usr/bin/rm -f /etc/buildkite-agent/agent-token /run/hostpanel-buildkite/checkout-deploy-key
