#!/usr/bin/env python3
"""Run the source-release builder with deterministic phase isolation."""

from __future__ import annotations

import importlib.util
import os
import pathlib
import stat
import sys
from types import ModuleType
from typing import Sequence


BUILDER_PATH = pathlib.Path(__file__).with_name("build-source-release.py")
ATTESTATION_PATH = pathlib.Path(__file__).with_name("generate-source-attestations.py")
BYTECODE_SUFFIXES = {".pyc", ".pyo"}


def load_module(name: str, path: pathlib.Path) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_builder() -> ModuleType:
    return load_module("hostpanel_source_release_builder", BUILDER_PATH)


def load_attestations() -> ModuleType:
    return load_module("hostpanel_source_attestations", ATTESTATION_PATH)


def overlay_archive_path(destination: pathlib.Path) -> pathlib.Path:
    if destination.name in ("", ".", ".."):
        raise ValueError("overlay destination must have a safe final component")
    return destination.parent / f"{destination.name}.tar"


def _unlink_bytecode(path: pathlib.Path) -> None:
    metadata = path.lstat()
    if not stat.S_ISREG(metadata.st_mode) or metadata.st_nlink != 1:
        raise RuntimeError(f"unsafe generated bytecode entry: {path}")
    path.unlink()


def remove_python_bytecode(source_root: pathlib.Path) -> None:
    cache_directories = sorted(
        (path for path in source_root.rglob("__pycache__")),
        key=lambda path: (len(path.parts), path.as_posix()),
        reverse=True,
    )
    for cache_directory in cache_directories:
        if not cache_directory.exists() and not cache_directory.is_symlink():
            continue
        metadata = cache_directory.lstat()
        if not stat.S_ISDIR(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
            raise RuntimeError(f"unsafe Python cache directory: {cache_directory}")
        for entry in sorted(cache_directory.iterdir(), key=lambda path: path.name):
            entry_metadata = entry.lstat()
            if (
                stat.S_ISREG(entry_metadata.st_mode)
                and entry.suffix in BYTECODE_SUFFIXES
                and entry_metadata.st_nlink == 1
            ):
                entry.unlink()
            else:
                raise RuntimeError(f"unexpected Python cache entry: {entry}")
        cache_directory.rmdir()

    for suffix in sorted(BYTECODE_SUFFIXES):
        for path in sorted(source_root.rglob(f"*{suffix}"), key=lambda item: item.as_posix()):
            _unlink_bytecode(path)


def normalize_source_modes(source_root: pathlib.Path) -> None:
    """Make the tree mode-identical before manifesting and archiving.

    Generator subprocesses inherit the caller's umask. Without this pass, the
    same reviewed source can produce a 0600 manifest under a private guest
    umask while the canonical tar writer correctly emits 0644, causing a false
    attestation mismatch. Source releases intentionally support only 0755
    directories and 0644/0755 regular files.
    """

    entries = sorted(
        source_root.rglob("*"),
        key=lambda path: path.relative_to(source_root).as_posix(),
    )
    for path in entries:
        metadata = path.lstat()
        if stat.S_ISLNK(metadata.st_mode):
            raise RuntimeError(f"source tree contains a symbolic link: {path}")
        if stat.S_ISDIR(metadata.st_mode):
            os.chmod(path, 0o755)
        elif stat.S_ISREG(metadata.st_mode):
            if metadata.st_nlink != 1:
                raise RuntimeError(f"source file has multiple hard links: {path}")
            os.chmod(path, 0o755 if metadata.st_mode & stat.S_IXUSR else 0o644)
        else:
            raise RuntimeError(f"source tree contains an unsupported entry: {path}")


def install_phase_isolation(
    builder: ModuleType,
    attestations: ModuleType | None = None,
) -> None:
    if attestations is None:
        attestations = load_attestations()

    def export_overlay(
        root: pathlib.Path,
        commit: str,
        paths: Sequence[str],
        destination: pathlib.Path,
    ) -> None:
        for path in paths:
            builder.run_git(root, "cat-file", "-e", f"{commit}:{path}")
        archive_path = overlay_archive_path(destination)
        with archive_path.open("xb") as output:
            builder.run(
                [
                    "git",
                    "-C",
                    str(root),
                    "archive",
                    "--format=tar",
                    commit,
                    "--",
                    *paths,
                ],
                stdout=output,
            )
        builder.extract_tar_safely(
            archive_path,
            destination,
            require_single_root=False,
        )

    original_write_archive = builder.write_deterministic_archive

    def write_deterministic_archive(
        source_root: pathlib.Path,
        output_path: pathlib.Path,
        identity,
        timestamp: int,
    ) -> None:
        remove_python_bytecode(source_root)
        normalize_source_modes(source_root)
        attestations.generate_attestations(
            source_root,
            source_version=identity.source_version,
            release_id=identity.release_id,
            timestamp=timestamp,
        )
        original_write_archive(source_root, output_path, identity, timestamp)
        attestations.verify_archive_attestations(
            output_path,
            root_name=identity.archive_root,
            source_version=identity.source_version,
            release_id=identity.release_id,
        )
        attestations.copy_attestations(source_root, output_path.parent)

    builder.export_overlay = export_overlay
    builder.write_deterministic_archive = write_deterministic_archive


def main(argv: Sequence[str] | None = None) -> int:
    builder = load_builder()
    install_phase_isolation(builder)
    return builder.main(argv)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        handled_errors = tuple(
            error_type
            for module_name, error_name in (
                ("hostpanel_source_release_builder", "ReleaseBuildError"),
                ("hostpanel_source_attestations", "AttestationError"),
            )
            if (module := sys.modules.get(module_name)) is not None
            and isinstance((error_type := getattr(module, error_name, None)), type)
        )
        if handled_errors and isinstance(error, handled_errors):
            print(f"Source release build failed: {error}", file=os.sys.stderr)
            raise SystemExit(1)
        raise
