#!/usr/bin/env python3
"""Run the source-release builder with deterministic phase isolation."""

from __future__ import annotations

import importlib.util
import os
import pathlib
import stat
import sys
from types import ModuleType
from typing import Sequence


BUILDER_PATH = pathlib.Path(__file__).with_name("build-source-release.py")
BYTECODE_SUFFIXES = {".pyc", ".pyo"}


def load_builder() -> ModuleType:
    spec = importlib.util.spec_from_file_location("hostpanel_source_release_builder", BUILDER_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load source release builder")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def overlay_archive_path(destination: pathlib.Path) -> pathlib.Path:
    if destination.name in ("", ".", ".."):
        raise ValueError("overlay destination must have a safe final component")
    return destination.parent / f"{destination.name}.tar"


def _unlink_bytecode(path: pathlib.Path) -> None:
    metadata = path.lstat()
    if not stat.S_ISREG(metadata.st_mode) or metadata.st_nlink != 1:
        raise RuntimeError(f"unsafe generated bytecode entry: {path}")
    path.unlink()


def remove_python_bytecode(source_root: pathlib.Path) -> None:
    cache_directories = sorted(
        (path for path in source_root.rglob("__pycache__")),
        key=lambda path: (len(path.parts), path.as_posix()),
        reverse=True,
    )
    for cache_directory in cache_directories:
        if not cache_directory.exists() and not cache_directory.is_symlink():
            continue
        metadata = cache_directory.lstat()
        if not stat.S_ISDIR(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
            raise RuntimeError(f"unsafe Python cache directory: {cache_directory}")
        for entry in sorted(cache_directory.iterdir(), key=lambda path: path.name):
            entry_metadata = entry.lstat()
            if (
                stat.S_ISREG(entry_metadata.st_mode)
                and entry.suffix in BYTECODE_SUFFIXES
                and entry_metadata.st_nlink == 1
            ):
                entry.unlink()
            else:
                raise RuntimeError(f"unexpected Python cache entry: {entry}")
        cache_directory.rmdir()

    for suffix in sorted(BYTECODE_SUFFIXES):
        for path in sorted(source_root.rglob(f"*{suffix}"), key=lambda item: item.as_posix()):
            _unlink_bytecode(path)


def install_phase_isolation(builder: ModuleType) -> None:
    def export_overlay(
        root: pathlib.Path,
        commit: str,
        paths: Sequence[str],
        destination: pathlib.Path,
    ) -> None:
        for path in paths:
            builder.run_git(root, "cat-file", "-e", f"{commit}:{path}")
        archive_path = overlay_archive_path(destination)
        with archive_path.open("xb") as output:
            builder.run(
                [
                    "git",
                    "-C",
                    str(root),
                    "archive",
                    "--format=tar",
                    commit,
                    "--",
                    *paths,
                ],
                stdout=output,
            )
        builder.extract_tar_safely(
            archive_path,
            destination,
            require_single_root=False,
        )

    original_write_archive = builder.write_deterministic_archive

    def write_deterministic_archive(
        source_root: pathlib.Path,
        output_path: pathlib.Path,
        identity,
        timestamp: int,
    ) -> None:
        remove_python_bytecode(source_root)
        original_write_archive(source_root, output_path, identity, timestamp)

    builder.export_overlay = export_overlay
    builder.write_deterministic_archive = write_deterministic_archive


def main(argv: Sequence[str] | None = None) -> int:
    builder = load_builder()
    install_phase_isolation(builder)
    return builder.main(argv)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        builder_error = getattr(
            sys.modules.get("hostpanel_source_release_builder"),
            "ReleaseBuildError",
            (),
        )
        if builder_error and isinstance(error, builder_error):
            print(f"Source release build failed: {error}", file=os.sys.stderr)
            raise SystemExit(1)
        raise
